/// Lookup table for common DTC codes.
/// Extend this as needed — in a production app this would come from a
/// bundled SQLite database or a remote API.
class DtcDecoder {
  DtcDecoder._();

  static const Map<String, String> _descriptions = {
    // ── Fuel & Air Metering ────────────────────────────────────────────────
    'P0010': 'Intake Camshaft Position Actuator Circuit (Bank 1)',
    'P0011': 'Intake Camshaft Position Timing Over-Advanced (Bank 1)',
    'P0012': 'Intake Camshaft Position Timing Over-Retarded (Bank 1)',
    'P0013': 'Exhaust Camshaft Position Actuator Circuit (Bank 1)',
    'P0014': 'Exhaust Camshaft Position Timing Over-Advanced (Bank 1)',
    'P0015': 'Exhaust Camshaft Position Timing Over-Retarded (Bank 1)',
    'P0016': 'Crankshaft Position / Camshaft Position Correlation (Bank 1 Sensor A)',
    'P0017': 'Crankshaft Position / Camshaft Position Correlation (Bank 1 Sensor B)',
    'P0020': 'Intake Camshaft Position Actuator Circuit (Bank 2)',
    'P0021': 'Intake Camshaft Position Timing Over-Advanced (Bank 2)',
    'P0022': 'Intake Camshaft Position Timing Over-Retarded (Bank 2)',
    'P0030': 'HO2S Heater Control Circuit (Bank 1, Sensor 1)',
    'P0031': 'HO2S Heater Control Circuit Low (Bank 1, Sensor 1)',
    'P0032': 'HO2S Heater Control Circuit High (Bank 1, Sensor 1)',
    'P0036': 'HO2S Heater Control Circuit (Bank 1, Sensor 2)',
    'P0037': 'HO2S Heater Control Circuit Low (Bank 1, Sensor 2)',
    'P0038': 'HO2S Heater Control Circuit High (Bank 1, Sensor 2)',
    'P0050': 'HO2S Heater Control Circuit (Bank 2, Sensor 1)',
    'P0056': 'HO2S Heater Control Circuit (Bank 2, Sensor 2)',
    'P0087': 'Fuel Rail / System Pressure Too Low',
    'P0088': 'Fuel Rail / System Pressure Too High',
    'P0089': 'Fuel Pressure Regulator Performance',
    'P0090': 'Fuel Pressure Regulator Control Circuit',
    'P0093': 'Fuel System Leak Detected (Large Leak)',
    'P0095': 'Intake Air Temperature Sensor 2 Circuit',
    'P0100': 'Mass Air Flow Circuit Malfunction',
    'P0101': 'Mass Air Flow Circuit Range / Performance',
    'P0102': 'Mass Air Flow Circuit Low Input',
    'P0103': 'Mass Air Flow Circuit High Input',
    'P0104': 'Mass Air Flow Circuit Intermittent',
    'P0106': 'Manifold Absolute Pressure / Barometric Pressure Circuit Range / Performance',
    'P0107': 'Manifold Absolute Pressure / Barometric Pressure Circuit Low Input',
    'P0108': 'Manifold Absolute Pressure / Barometric Pressure Circuit High Input',
    'P0110': 'Intake Air Temperature Circuit Malfunction',
    'P0111': 'Intake Air Temperature Circuit Range / Performance',
    'P0112': 'Intake Air Temperature Circuit Low Input',
    'P0113': 'Intake Air Temperature Circuit High Input',
    'P0116': 'Engine Coolant Temperature Circuit Range / Performance',
    'P0117': 'Engine Coolant Temperature Circuit Low Input',
    'P0118': 'Engine Coolant Temperature Circuit High Input',
    'P0120': 'Throttle Position Sensor / Switch A Circuit Malfunction',
    'P0121': 'Throttle Position Sensor / Switch A Circuit Range / Performance',
    'P0122': 'Throttle Position Sensor / Switch A Circuit Low Input',
    'P0123': 'Throttle Position Sensor / Switch A Circuit High Input',
    'P0125': 'Insufficient Coolant Temperature for Closed-Loop Fuel Control',
    'P0128': 'Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)',
    'P0130': 'O2 Sensor Circuit Malfunction (Bank 1, Sensor 1)',
    'P0131': 'O2 Sensor Circuit Low Voltage (Bank 1, Sensor 1)',
    'P0132': 'O2 Sensor Circuit High Voltage (Bank 1, Sensor 1)',
    'P0133': 'O2 Sensor Slow Response (Bank 1, Sensor 1)',
    'P0134': 'O2 Sensor No Activity Detected (Bank 1, Sensor 1)',
    'P0135': 'O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 1)',
    'P0136': 'O2 Sensor Circuit Malfunction (Bank 1, Sensor 2)',
    'P0137': 'O2 Sensor Circuit Low Voltage (Bank 1, Sensor 2)',
    'P0138': 'O2 Sensor Circuit High Voltage (Bank 1, Sensor 2)',
    'P0139': 'O2 Sensor Slow Response (Bank 1, Sensor 2)',
    'P0140': 'O2 Sensor No Activity Detected (Bank 1, Sensor 2)',
    'P0141': 'O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 2)',
    'P0150': 'O2 Sensor Circuit Malfunction (Bank 2, Sensor 1)',
    'P0151': 'O2 Sensor Circuit Low Voltage (Bank 2, Sensor 1)',
    'P0152': 'O2 Sensor Circuit High Voltage (Bank 2, Sensor 1)',
    'P0153': 'O2 Sensor Slow Response (Bank 2, Sensor 1)',
    'P0154': 'O2 Sensor No Activity Detected (Bank 2, Sensor 1)',
    'P0155': 'O2 Sensor Heater Circuit Malfunction (Bank 2, Sensor 1)',
    'P0156': 'O2 Sensor Circuit Malfunction (Bank 2, Sensor 2)',
    'P0157': 'O2 Sensor Circuit Low Voltage (Bank 2, Sensor 2)',
    'P0158': 'O2 Sensor Circuit High Voltage (Bank 2, Sensor 2)',
    'P0159': 'O2 Sensor Slow Response (Bank 2, Sensor 2)',
    'P0160': 'O2 Sensor No Activity Detected (Bank 2, Sensor 2)',
    'P0161': 'O2 Sensor Heater Circuit Malfunction (Bank 2, Sensor 2)',
    'P0170': 'Fuel Trim Malfunction (Bank 1)',
    'P0171': 'System Too Lean (Bank 1)',
    'P0172': 'System Too Rich (Bank 1)',
    'P0173': 'Fuel Trim Malfunction (Bank 2)',
    'P0174': 'System Too Lean (Bank 2)',
    'P0175': 'System Too Rich (Bank 2)',
    'P0176': 'Fuel Composition Sensor Circuit Malfunction',
    'P0180': 'Fuel Temperature Sensor A Circuit Malfunction',
    'P0190': 'Fuel Rail Pressure Sensor Circuit Malfunction',
    'P0191': 'Fuel Rail Pressure Sensor Circuit Range / Performance',
    'P0192': 'Fuel Rail Pressure Sensor Circuit Low Input',
    'P0193': 'Fuel Rail Pressure Sensor Circuit High Input',
    'P0194': 'Fuel Rail Pressure Sensor Circuit Intermittent',
    'P0195': 'Engine Oil Temperature Sensor Malfunction',
    'P0196': 'Engine Oil Temperature Sensor Range / Performance',
    'P0200': 'Injector Circuit Malfunction',
    'P0201': 'Injector Circuit Malfunction — Cylinder 1',
    'P0202': 'Injector Circuit Malfunction — Cylinder 2',
    'P0203': 'Injector Circuit Malfunction — Cylinder 3',
    'P0204': 'Injector Circuit Malfunction — Cylinder 4',
    'P0205': 'Injector Circuit Malfunction — Cylinder 5',
    'P0206': 'Injector Circuit Malfunction — Cylinder 6',
    'P0207': 'Injector Circuit Malfunction — Cylinder 7',
    'P0208': 'Injector Circuit Malfunction — Cylinder 8',
    'P0215': 'Engine Shutoff Solenoid Malfunction',
    'P0217': 'Engine Overtemperature Condition',
    'P0218': 'Transmission Over Temperature Condition',
    'P0219': 'Engine Overspeed Condition',
    'P0220': 'Throttle Position Sensor / Switch B Circuit',
    'P0221': 'Throttle Position Sensor / Switch B Circuit Range / Performance',
    'P0222': 'Throttle Position Sensor / Switch B Circuit Low Input',
    'P0223': 'Throttle Position Sensor / Switch B Circuit High Input',
    'P0230': 'Fuel Pump Primary Circuit Malfunction',
    'P0231': 'Fuel Pump Secondary Circuit Low',
    'P0232': 'Fuel Pump Secondary Circuit High',
    'P0243': 'Turbocharger Wastegate Solenoid A',
    'P0244': 'Turbocharger Wastegate Solenoid A Range / Performance',
    'P0245': 'Turbocharger Wastegate Solenoid A Low',
    'P0246': 'Turbocharger Wastegate Solenoid A High',
    'P0251': 'Injection Pump Fuel Metering Control A (Cam/Rotor/Injector)',
    'P0261': 'Cylinder 1 Injector Circuit Low',
    'P0262': 'Cylinder 1 Injector Circuit High',
    'P0263': 'Cylinder 1 Contribution / Balance Fault',
    'P0264': 'Cylinder 2 Injector Circuit Low',
    'P0265': 'Cylinder 2 Injector Circuit High',
    'P0266': 'Cylinder 2 Contribution / Balance Fault',
    'P0267': 'Cylinder 3 Injector Circuit Low',
    'P0268': 'Cylinder 3 Injector Circuit High',
    'P0269': 'Cylinder 3 Contribution / Balance Fault',
    'P0270': 'Cylinder 4 Injector Circuit Low',
    'P0271': 'Cylinder 4 Injector Circuit High',
    'P0272': 'Cylinder 4 Contribution / Balance Fault',

    // ── Ignition / Misfire ─────────────────────────────────────────────────
    'P0300': 'Random / Multiple Cylinder Misfire Detected',
    'P0301': 'Cylinder 1 Misfire Detected',
    'P0302': 'Cylinder 2 Misfire Detected',
    'P0303': 'Cylinder 3 Misfire Detected',
    'P0304': 'Cylinder 4 Misfire Detected',
    'P0305': 'Cylinder 5 Misfire Detected',
    'P0306': 'Cylinder 6 Misfire Detected',
    'P0307': 'Cylinder 7 Misfire Detected',
    'P0308': 'Cylinder 8 Misfire Detected',
    'P0315': 'Crankshaft Position System Variation Not Learned',
    'P0316': 'Misfire Detected on Startup (First 1000 Revolutions)',
    'P0320': 'Ignition / Distributor Engine Speed Input Circuit Malfunction',
    'P0321': 'Ignition / Distributor Engine Speed Input Circuit Range / Performance',
    'P0325': 'Knock Sensor 1 Circuit Malfunction (Bank 1)',
    'P0326': 'Knock Sensor 1 Circuit Range / Performance (Bank 1)',
    'P0327': 'Knock Sensor 1 Circuit Low Input (Bank 1)',
    'P0328': 'Knock Sensor 1 Circuit High Input (Bank 1)',
    'P0330': 'Knock Sensor 2 Circuit Malfunction (Bank 2)',
    'P0332': 'Knock Sensor 2 Circuit Low Input (Bank 2)',
    'P0333': 'Knock Sensor 2 Circuit High Input (Bank 2)',
    'P0335': 'Crankshaft Position Sensor A Circuit Malfunction',
    'P0336': 'Crankshaft Position Sensor A Circuit Range / Performance',
    'P0340': 'Camshaft Position Sensor A Circuit Malfunction (Bank 1)',
    'P0341': 'Camshaft Position Sensor A Circuit Range / Performance (Bank 1)',
    'P0345': 'Camshaft Position Sensor A Circuit Malfunction (Bank 2)',
    'P0346': 'Camshaft Position Sensor A Circuit Range / Performance (Bank 2)',
    'P0350': 'Ignition Coil Primary / Secondary Circuit Malfunction',
    'P0351': 'Ignition Coil A Primary / Secondary Circuit Malfunction',
    'P0352': 'Ignition Coil B Primary / Secondary Circuit Malfunction',
    'P0353': 'Ignition Coil C Primary / Secondary Circuit Malfunction',
    'P0354': 'Ignition Coil D Primary / Secondary Circuit Malfunction',
    'P0355': 'Ignition Coil E Primary / Secondary Circuit Malfunction',
    'P0356': 'Ignition Coil F Primary / Secondary Circuit Malfunction',

    // ── Catalytic Converter ────────────────────────────────────────────────
    'P0420': 'Catalyst System Efficiency Below Threshold (Bank 1)',
    'P0421': 'Warm Up Catalyst Efficiency Below Threshold (Bank 1)',
    'P0422': 'Main Catalyst Efficiency Below Threshold (Bank 1)',
    'P0430': 'Catalyst System Efficiency Below Threshold (Bank 2)',
    'P0431': 'Warm Up Catalyst Efficiency Below Threshold (Bank 2)',
    'P0432': 'Main Catalyst Efficiency Below Threshold (Bank 2)',

    // ── EGR / Evaporative ──────────────────────────────────────────────────
    'P0400': 'Exhaust Gas Recirculation Flow Malfunction',
    'P0401': 'Exhaust Gas Recirculation Flow Insufficient',
    'P0402': 'Exhaust Gas Recirculation Flow Excessive',
    'P0403': 'Exhaust Gas Recirculation Circuit Malfunction',
    'P0404': 'Exhaust Gas Recirculation Circuit Range / Performance',
    'P0405': 'Exhaust Gas Recirculation Sensor A Circuit Low',
    'P0406': 'Exhaust Gas Recirculation Sensor A Circuit High',
    'P0410': 'Secondary Air Injection System Malfunction',
    'P0411': 'Secondary Air Injection System Incorrect Flow',
    'P0440': 'Evaporative Emission Control System Malfunction',
    'P0441': 'Evaporative Emission Control System Incorrect Purge Flow',
    'P0442': 'Evaporative Emission Control System Leak Detected (small)',
    'P0443': 'Evaporative Emission Control System Purge Control Valve Circuit',
    'P0446': 'Evaporative Emission Control System Vent Control Circuit',
    'P0447': 'Evaporative Emission Control System Vent Control Circuit Open',
    'P0448': 'Evaporative Emission Control System Vent Control Circuit Shorted',
    'P0449': 'Evaporative Emission Control System Vent Valve / Solenoid Circuit',
    'P0450': 'Evaporative Emission Control System Pressure Sensor',
    'P0451': 'Evaporative Emission Control System Pressure Sensor Range / Performance',
    'P0452': 'Evaporative Emission Control System Pressure Sensor Low Input',
    'P0453': 'Evaporative Emission Control System Pressure Sensor High Input',
    'P0455': 'Evaporative Emission Control System Leak Detected (large)',
    'P0456': 'Evaporative Emission Control System Leak Detected (very small)',

    // ── Engine Speed / Idle ────────────────────────────────────────────────
    'P0500': 'Vehicle Speed Sensor Malfunction',
    'P0501': 'Vehicle Speed Sensor Range / Performance',
    'P0503': 'Vehicle Speed Sensor Intermittent / Erratic / High',
    'P0505': 'Idle Control System Malfunction',
    'P0506': 'Idle Control System RPM Lower Than Expected',
    'P0507': 'Idle Control System RPM Higher Than Expected',
    'P0510': 'Closed Throttle Position Switch Malfunction',
    'P0520': 'Engine Oil Pressure Sensor / Switch Circuit Malfunction',
    'P0521': 'Engine Oil Pressure Sensor / Switch Range / Performance',
    'P0522': 'Engine Oil Pressure Sensor / Switch Low Voltage',
    'P0523': 'Engine Oil Pressure Sensor / Switch High Voltage',
    'P0524': 'Engine Oil Pressure Too Low',
    'P0530': 'A/C Refrigerant Pressure Sensor Circuit',
    'P0532': 'A/C Refrigerant Pressure Sensor Circuit Low Input',
    'P0533': 'A/C Refrigerant Pressure Sensor Circuit High Input',

    // ── Engine Temperature / Cooling ───────────────────────────────────────
    'P0115': 'Engine Coolant Temperature Circuit Malfunction',

    // ── Battery / Charging ────────────────────────────────────────────────
    'P0550': 'Power Steering Pressure Sensor Circuit Malfunction',
    'P0560': 'System Voltage Malfunction',
    'P0562': 'System Voltage Low',
    'P0563': 'System Voltage High',
    'P0571': 'Cruise Control / Brake Switch A Circuit Malfunction',

    // ── Communication / ECU ──────────────────────────────────────────────
    'P0600': 'Serial Communication Link Malfunction',
    'P0601': 'Internal Control Module Memory Check Sum Error',
    'P0602': 'Control Module Programming Error',
    'P0603': 'Internal Control Module KAM Error',
    'P0604': 'Internal Control Module RAM Error',
    'P0605': 'Internal Control Module ROM Error',
    'P0606': 'PCM Processor Fault',
    'P0607': 'Control Module Performance',
    'P0610': 'Control Module Vehicle Options Error',
    'P0620': 'Generator Control Circuit Malfunction',
    'P0625': 'Generator Field Terminal Circuit Low',
    'P0626': 'Generator Field Terminal Circuit High',
    'P0630': 'VIN Not Programmed or Incompatible — ECM / PCM',
    'P0645': 'A/C Clutch Relay Control Circuit',
    'P0650': 'Malfunction Indicator Lamp (MIL) Control Circuit',

    // ── Transmission ──────────────────────────────────────────────────────
    'P0700': 'Transmission Control System Malfunction',
    'P0705': 'Transmission Range Sensor Circuit Malfunction',
    'P0706': 'Transmission Range Sensor Circuit Range / Performance',
    'P0710': 'Transmission Fluid Temperature Sensor Circuit Malfunction',
    'P0711': 'Transmission Fluid Temperature Sensor Circuit Range / Performance',
    'P0715': 'Input / Turbine Speed Sensor Circuit Malfunction',
    'P0716': 'Input / Turbine Speed Sensor Circuit Range / Performance',
    'P0717': 'Input / Turbine Speed Sensor No Signal',
    'P0720': 'Output Speed Sensor Circuit Malfunction',
    'P0721': 'Output Speed Sensor Circuit Range / Performance',
    'P0722': 'Output Speed Sensor No Signal',
    'P0725': 'Engine Speed Input Circuit Malfunction',
    'P0730': 'Incorrect Gear Ratio',
    'P0731': 'Gear 1 Incorrect Ratio',
    'P0732': 'Gear 2 Incorrect Ratio',
    'P0733': 'Gear 3 Incorrect Ratio',
    'P0734': 'Gear 4 Incorrect Ratio',
    'P0735': 'Gear 5 Incorrect Ratio',
    'P0740': 'Torque Converter Clutch Circuit Malfunction',
    'P0741': 'Torque Converter Clutch Circuit Performance or Stuck Off',
    'P0742': 'Torque Converter Clutch Circuit Stuck On',
    'P0743': 'Torque Converter Clutch Circuit Electrical',
    'P0744': 'Torque Converter Clutch Circuit Intermittent',
    'P0750': 'Shift Solenoid A Malfunction',
    'P0751': 'Shift Solenoid A Performance or Stuck Off',
    'P0752': 'Shift Solenoid A Stuck On',
    'P0755': 'Shift Solenoid B Malfunction',
    'P0756': 'Shift Solenoid B Performance or Stuck Off',
    'P0757': 'Shift Solenoid B Stuck On',
    'P0760': 'Shift Solenoid C Malfunction',
    'P0765': 'Shift Solenoid D Malfunction',
    'P0770': 'Shift Solenoid E Malfunction',
    'P0775': 'Pressure Control Solenoid B',
    'P0780': 'Shift Malfunction',
    'P0781': '1-2 Shift Malfunction',
    'P0782': '2-3 Shift Malfunction',
    'P0783': '3-4 Shift Malfunction',
    'P0784': '4-5 Shift Malfunction',

    // ── Diesel / Turbo ──────────────────────────────────────────────────────
    'P0234': 'Turbocharger / Supercharger Overboost Condition',
    'P0235': 'Turbocharger Boost Sensor A Circuit',
    'P0236': 'Turbocharger Boost Sensor A Circuit Range / Performance',
    'P0237': 'Turbocharger Boost Sensor A Circuit Low',
    'P0238': 'Turbocharger Boost Sensor A Circuit High',
    'P0299': 'Turbocharger / Supercharger Underboost',
    'P0380': 'Glow Plug / Heater Circuit A Malfunction',
    'P0381': 'Glow Plug / Heater Indicator Circuit Malfunction',

    // ── Body (B codes) ──────────────────────────────────────────────────────
    'B0001': 'Driver Frontal Stage 1 Deployment Control',
    'B0002': 'Driver Frontal Stage 2 Deployment Control',
    'B0010': 'Passenger Frontal Stage 1 Deployment Control',
    'B0020': 'Driver Side / Side Curtain Stage 1 Deployment Control',
    'B0050': 'Driver Seat Belt Pretensioner Deployment Control',
    'B0081': 'Passenger Seat Belt Pretensioner Deployment Control',
    'B0100': 'Electronic Frontal Sensor 1',
    'B1000': 'ECU Malfunction (Body Control Module)',
    'B1200': 'Climate Control Pushbutton Circuit Fault',
    'B1318': 'Battery Voltage Low',
    'B1325': 'Battery Voltage High',
    'B1342': 'ECU Defective',
    'B1352': 'Ignition Key-In Circuit Failure',
    'B1601': 'PATS Received Incorrect Key Code From Ignition Key Transponder',
    'B1602': 'PATS Received Invalid Format of Key Code From Ignition Key Transponder',
    'B2799': 'Immobilizer / Transponder Key Not Recognized',

    // ── Chassis (C codes) ───────────────────────────────────────────────────
    'C0035': 'Left Front Wheel Speed Sensor Circuit',
    'C0040': 'Right Front Wheel Speed Sensor Circuit',
    'C0045': 'Left Rear Wheel Speed Sensor Circuit',
    'C0050': 'Right Rear Wheel Speed Sensor Circuit',
    'C0060': 'Left Front ABS Solenoid #1 Circuit',
    'C0065': 'Right Front ABS Solenoid #1 Circuit',
    'C0070': 'Left Rear ABS Solenoid #1 Circuit',
    'C0075': 'Right Rear ABS Solenoid #1 Circuit',
    'C0110': 'Pump Motor Circuit Malfunction',
    'C0131': 'ABS / TCS System Pressure Circuit Low',
    'C0161': 'ABS / TCS Brake Switch Circuit Malfunction',
    'C0221': 'Right Front Wheel Speed Sensor Signal Missing',
    'C0222': 'Left Front Wheel Speed Sensor Signal Missing',
    'C0223': 'Right Rear Wheel Speed Sensor Signal Missing',
    'C0224': 'Left Rear Wheel Speed Sensor Signal Missing',
    'C0236': 'Rear Wheel Speed Sensor Circuit Open or Shorted',
    'C0265': 'EBCM Motor Relay Circuit',
    'C0267': 'Pump Motor Circuit Open or Shorted',
    'C0550': 'ECU Malfunction (Electronic Brake Control Module)',
    'C1095': 'ABS Hydraulic Pump Motor Circuit Failure',
    'C1145': 'Right Front Wheel Speed Sensor Input Circuit Failure',
    'C1155': 'Left Front Wheel Speed Sensor Input Circuit Failure',
    'C1165': 'Right Rear Wheel Speed Sensor Input Circuit Failure',
    'C1175': 'Left Rear Wheel Speed Sensor Input Circuit Failure',
    'C1185': 'ABS Power Relay Output Circuit Failure',
    'C1233': 'Left Front Wheel Speed Sensor Input Signal Missing',
    'C1234': 'Right Front Wheel Speed Sensor Input Signal Missing',
    'C1235': 'Left Rear Wheel Speed Sensor Input Signal Missing',
    'C1236': 'Right Rear Wheel Speed Sensor Input Signal Missing',

    // ── Network (U codes) ───────────────────────────────────────────────────
    'U0001': 'High Speed CAN Communication Bus',
    'U0002': 'High Speed CAN Communication Bus Performance',
    'U0003': 'High Speed CAN Communication Bus (+) Open',
    'U0004': 'High Speed CAN Communication Bus (+) Low',
    'U0005': 'High Speed CAN Communication Bus (+) High',
    'U0006': 'High Speed CAN Communication Bus (−) Open',
    'U0007': 'High Speed CAN Communication Bus (−) Low',
    'U0008': 'High Speed CAN Communication Bus (−) High',
    'U0010': 'Medium Speed CAN Communication Bus',
    'U0073': 'Control Module Communication Bus Off',
    'U0100': 'Lost Communication With ECM / PCM',
    'U0101': 'Lost Communication With TCM',
    'U0102': 'Lost Communication With Transfer Case Control Module',
    'U0103': 'Lost Communication With Gear Shift Module',
    'U0104': 'Lost Communication With Cruise Control Module',
    'U0105': 'Lost Communication With Fuel Injector Control Module',
    'U0106': 'Lost Communication With Glow Plug Control Module',
    'U0107': 'Lost Communication With Throttle Actuator Control Module',
    'U0109': 'Lost Communication With Fuel Pump Control Module',
    'U0110': 'Lost Communication With Drive Motor Control Module',
    'U0111': 'Lost Communication With Battery Energy Control Module',
    'U0121': 'Lost Communication With ABS Control Module',
    'U0122': 'Lost Communication With Vehicle Dynamics Control Module',
    'U0126': 'Lost Communication With Steering Angle Sensor Module',
    'U0128': 'Lost Communication With Park Brake Control Module',
    'U0131': 'Lost Communication With Power Steering Control Module',
    'U0140': 'Lost Communication With Body Control Module',
    'U0141': 'Lost Communication With Body Control Module A',
    'U0151': 'Lost Communication With Restraints Control Module',
    'U0155': 'Lost Communication With Instrument Panel Cluster',
    'U0164': 'Lost Communication With HVAC Control Module',
    'U0167': 'Lost Communication With Vehicle Immobilizer Control Module',
    'U0184': 'Lost Communication With Radio',
    'U0199': 'Lost Communication With Door Control Module A',
    'U0235': 'Lost Communication With Cruise Control Front Distance Range Sensor',
    'U0300': 'Internal Control Module Software Incompatibility',
    'U0401': 'Invalid Data Received From ECM / PCM',
    'U0402': 'Invalid Data Received From TCM',
    'U0404': 'Invalid Data Received From Gear Shift Module',
    'U0416': 'Invalid Data Received From Vehicle Dynamics Control Module',
    'U0426': 'Invalid Data Received From Steering Angle Sensor Module',
  };

  /// Returns a human-readable description for [code], or a generic
  /// fallback if the code is not in the table.
  static String describe(String code) {
    return _descriptions[code.toUpperCase()] ??
        'Unknown fault code ($code) — consult a mechanic';
  }

  /// Returns the severity label based on DTC category.
  static DtcSeverity severity(String code) {
    if (code.isEmpty) return DtcSeverity.unknown;
    return switch (code[0].toUpperCase()) {
      'P' => DtcSeverity.powertrain,
      'C' => DtcSeverity.chassis,
      'B' => DtcSeverity.body,
      'U' => DtcSeverity.network,
      _ => DtcSeverity.unknown,
    };
  }
}

enum DtcSeverity {
  powertrain,
  chassis,
  body,
  network,
  unknown;

  String get label => switch (this) {
        DtcSeverity.powertrain => 'Powertrain',
        DtcSeverity.chassis => 'Chassis',
        DtcSeverity.body => 'Body',
        DtcSeverity.network => 'Network',
        DtcSeverity.unknown => 'Unknown',
      };
}
